// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: buckets.sql

package database

import (
	"context"
)

const createBucket = `-- name: CreateBucket :one
INSERT INTO buckets (name, account_id, access_key, secret_key)
VALUES ($1, $2, $3, $4)
RETURNING id, name, account_id, access_key, secret_key, created_at
`

type CreateBucketParams struct {
	Name      string `json:"name"`
	AccountID string `json:"account_id"`
	AccessKey string `json:"access_key"`
	SecretKey string `json:"secret_key"`
}

func (q *Queries) CreateBucket(ctx context.Context, arg CreateBucketParams) (Bucket, error) {
	row := q.db.QueryRowContext(ctx, createBucket,
		arg.Name,
		arg.AccountID,
		arg.AccessKey,
		arg.SecretKey,
	)
	var i Bucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccountID,
		&i.AccessKey,
		&i.SecretKey,
		&i.CreatedAt,
	)
	return i, err
}

const createSnapshot = `-- name: CreateSnapshot :one
INSERT INTO snapshots (bucket_id, obj_count, size_byte)
VALUES ($1, $2, $3)
RETURNING id, bucket_id, obj_count, size_byte, recorded_at
`

type CreateSnapshotParams struct {
	BucketID int32 `json:"bucket_id"`
	ObjCount int64 `json:"obj_count"`
	SizeByte int64 `json:"size_byte"`
}

func (q *Queries) CreateSnapshot(ctx context.Context, arg CreateSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, createSnapshot, arg.BucketID, arg.ObjCount, arg.SizeByte)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.BucketID,
		&i.ObjCount,
		&i.SizeByte,
		&i.RecordedAt,
	)
	return i, err
}

const getBucketByID = `-- name: GetBucketByID :one
SELECT id, name, account_id, access_key, secret_key, created_at FROM buckets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBucketByID(ctx context.Context, id int32) (Bucket, error) {
	row := q.db.QueryRowContext(ctx, getBucketByID, id)
	var i Bucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccountID,
		&i.AccessKey,
		&i.SecretKey,
		&i.CreatedAt,
	)
	return i, err
}

const listBuckets = `-- name: ListBuckets :many
SELECT id, name, account_id, access_key, secret_key, created_at FROM buckets
ORDER BY created_at DESC
`

func (q *Queries) ListBuckets(ctx context.Context) ([]Bucket, error) {
	rows, err := q.db.QueryContext(ctx, listBuckets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bucket
	for rows.Next() {
		var i Bucket
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AccountID,
			&i.AccessKey,
			&i.SecretKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshots = `-- name: ListSnapshots :many
SELECT id, bucket_id, obj_count, size_byte, recorded_at FROM snapshots
WHERE bucket_id = $1
ORDER BY recorded_at DESC
`

func (q *Queries) ListSnapshots(ctx context.Context, bucketID int32) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, listSnapshots, bucketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Snapshot
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(
			&i.ID,
			&i.BucketID,
			&i.ObjCount,
			&i.SizeByte,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
