// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Bucket struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	AccountID string    `json:"account_id"`
	AccessKey string    `json:"access_key"`
	SecretKey string    `json:"secret_key"`
	CreatedAt time.Time `json:"created_at"`
}

type Snapshot struct {
	ID         int32     `json:"id"`
	BucketID   int32     `json:"bucket_id"`
	ObjCount   int64     `json:"obj_count"`
	SizeByte   int64     `json:"size_byte"`
	RecordedAt time.Time `json:"recorded_at"`
}
